### ISSUE TITLE
hyperdb upgrade

### ISSUE THREAD

**Issue by joehand** [datproject/dat-node#196]
General Issue for tracking stuff around the upgrade to [hyperdb](https://github.com/mafintosh/hyperdb)-backed hyperdrive. Related hyperdrive PR: https://github.com/mafintosh/hyperdrive/pull/204

* Current branch: https://github.com/datproject/dat-node/tree/hyperdb
* Demo in dat-next: https://github.com/joehand/dat-next

- [ ] `lib/stats.js` update (probably good time to move back to hyperdrive-stats)
- [ ] file storage
  - [ ] hyperdrive support
  - [ ] dat-storage
  - [ ] `lib/storage.js` support
 
## Backwards Compatibility

**TODO: What needs to happen for backwards compatibility?**

## Modules Needing Changes

- [ ] hyperdrive-http
- [ ] hyperdrive-network-speed

## Multiwriter Features

**TODO: what multiwriter features included in first release?**

**Comment by okdistribute** [comment]
hyperdb is not happening anymore, but we may go to hyperdrive v10 soon if it gets out of beta
