### ISSUE TITLE
v4 roadmap 

### ISSUE THREAD

**Issue by joehand** [datproject/dat-node#236]
Work has started on dat-node v4 in #234. This issue will track the roadmap for the new version of dat-node. Here is where my priorities are:

* continue focus on single-dat management to supoprt CLI
* simple API for managing a single dat including: stats, importing, dat-json, global config management.
* support async/await, drop node v4 support - update all dat dependencies to support promises
* improve support for using multiple dat-node instances together in apps (e.g. using a [single swarm for multiple dats](https://github.com/karissa/hyperdiscovery/pull/18)). 
* Providing better visibility of other discovery options (using custom discovery services, etc.)
* being type aware (also, required/optional) for options passed to classes 

Would be curious to hear other folks blockers around dat-node and what they'd like to see in next version.

Thanks for discussion prompted by @RangerMauve for this.

**Comment by joehand** [comment]
I've been using https://github.com/joehand/dat-folders as a prototyping ground for some of this work.

**Comment by cblgh** [comment]
this is related to your last point, albeit i guess it needs groundwork elsewhere, but i'd be _really_ interested in being able to sync a dat sneakernet style (via a usb, email, [pigeon](https://i.cblgh.org/2019-04/3253DyH.png) or whatever :)

since it's distinct from importing files, i guess sneakernet replication would technically follow under _**Network**_ since it's a transport type

**Comment by joehand** [comment]
Update on this:

- [ ] async/await support:
  - [ ] implemented
  - [ ] update all tests https://github.com/datproject/dat-node/pull/235
  - [ ] update docs
- [ ] use hyperdiscovery
  - [ ] move from discovery-swarm to hyperdiscovery
  - [ ] tests/docs

**Comment by chartgerink** [comment]
Any way I can specifically contribute to this process? 

I just found this roadmap as I was trying to run something iteratively across a collection of Dats using  Promises, and it didn't work :')

I'm happy to contribute any way I can (e.g., testing, updating docs).

**Comment by joehand** [comment]
@chartgerink PR #235 is mostly about updating tests and docs at this point. Any help welcome! I've been using it in other projects mostly without issues at this point.

What issue are you having? I did a bit with iterating over dats here: https://github.com/joehand/dat-folders

**Comment by chartgerink** [comment]
Ah great! I just tested out what I was doing and it works based on the `async` branch, yes! :champagne: 

I wanted to get the writable property out for a cache I'm building across Dats, so I was doing something like 

```js
  let isOwner = await Dat(dirs[dir])
console.log(isOwner.writable)
```

which now seems to work :)

Would for the docs rewriting to things like this be worthwhile?


```js
let dat = await Dat('/my-data')
await dat.importFiles('/another-dir')

console.log('done importing another-dir')
```

<details>
 <summary>Old docs</summary>

```js
Dat('/my-data', function (err, dat) {
  if (err) throw err

  dat.importFiles('/another-dir', function (err) {
    console.log('done importing another-dir')
  })
})
```

</details>

**Comment by karissa** [comment]
cc @RangerMauve on new apis coming this summer

**Comment by RangerMauve** [comment]
Yeah, we're going to be getting a high level Dat SDK.

It's going to have a traditionally node.js API, and also a more beaker-like Promise based API.

You can follow progress here: https://github.com/datproject/sdk

**Comment by chartgerink** [comment]
Oh that sounds good. I totally missed that. Is there a roadmap somewhere about these plans?

I am a bit confused about what is going to happen to `dat-node` then? Is it obsolete in light of the SDK, is it simply additional, or something else?

**Comment by RangerMauve** [comment]
Hey! I'm going to update the [planning roadmap](https://github.com/datproject/planning/) with the SDK and Daemon stuff this week. Make sure to subscribe for changes there.

Once the SDK is out, dat-js and dat-node will need to be deprecated since it'll essentially be doing both of their roles with a clean cross-platform interface.

**Comment by chartgerink** [comment]
Thanks for that information! I'm building [`libscie-api`](https://github.com/libscie/api) using `dat-node` now, but I'll forego working on the daemon I was thinking of.

@RangerMauve feel free to utilize me for testing or whatever you think I can help with for the SDK :+1:

**Comment by okdistribute** [comment]
@joehand should we close this? do you plan on working on this anymore?
